export default [
  state => {
    const {entities} = state;
    const gateways = Object.values(entities.gateways)
      .filter(({id, deleting}) => !id.startsWith('autogenerated') && !deleting);
    return gateways;
  },
];
